[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = {version = "1", features = ["extra-traits"]}
proc-macro2 = "1"
